name : weekly status report application
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on:
  push:
    branches:
      - feature-ci/cd
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup_check
        run: echo "setup seccess"
        shell: bash
      - name: docker image builder
        run: docker build .
